### ISSUE TITLE
Sessions behave differently across subdomains

### ISSUE THREAD

**Issue by kjohnston** [newleaders/thincloud-authentication#41]
Given an app that allows login at apex and subdomain levels, but wishes to utilize the same session across all, I'm encountering the following issues:
- When logging in from the apex domain I can navigate to subdomains and keep my session.  However, I can only logout when doing so from the apex domain.
- When logging in from a subdomain the session I receive does not carry over to the apex domain or any other subdomains.

Settings used:

``` ruby
Thincloud::Authentication.configure do |config|
  config.cookie_options = {
    secure: Rails.env.in?(%(production staging)),
    domain: :all
  }
end
```

and in config/initializers/session_store.rb:

``` ruby
Foo::Application.config.session_store :cookie_store, key: '_foo_session', domain: :all
```

I'm using `http://lvh.me` to test this locally.

**Comment by phlipper** [comment]
@kjohnston a few things:
- As mentioned previously, the `secure` option is not needed since it is [provided by the engine](https://github.com/newleaders/thincloud-authentication/blob/master/lib/thincloud/authentication/authenticatable_controller.rb#L53), assuming you have the `config.force_ssl` option set.
- Personally, I've never had much luck with the `:all` option for the `domain` key when working with subdomains. This worked for me when testing the lvh.me domain: `domain: ".lvh.me"` - note the preceding `.` on the hostname.
- The `domain: :all` can be removed from your `session_store` configuration once your `domain` has been set properly in the `cookie_options`.

Let me know how that works out for you.

**Comment by kjohnston** [comment]
@phlipper, thanks for the followup on this and help in finding the proper config.

For future reference:
- Remove the `domain` setting from `session_store.rb`
- Apply an env-specific ".lvh.me" / ".mydomain.com" `domain` setting in `cookie_options` in the configuration block.
